version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=prod
    labels:
      - traefik.backend=www
      - traefik.frontend.rule=Host:www.southindiantrekkers.org,southindiantrekkers.org
      - traefik.frontend.redirect.regex=^https?://www.southindiantrekkers.org/(.*)
      - traefik.frontend.redirect.replacement=https://southindiantrekkers.org/$${1}
      - traefik.docker.network=proxy
      - traefik.port=3200
    networks:
      - internal
      - proxy
